= Overview: `pcond`

The next generation assertive programming library, inspired by valid4j<<v4j>>.

== Background

Didn't you get bored of writing a code like below repeatedly with Guava or any other small utility functions?

[source,java]
----
public class CheckArg {
  public void check() {
    checkArgument(i >= 0, "Argument was %s but expected nonnegative", i);
  }
}
----

We already say that the condition to be checked is `i >= 0`.
Why do we need to come up with a message that explains the violation commited by the value `i` every time we call the method?
Especially, methods in the `Preconditions` class is meant to check whether a given value meets a contract and its intention is to just forget handling values not meeting it.
We want a message to be human readable on violation to the extent where we are able to understand what is going on without visiting source code but we don't need to make it very user friendly.

Something like this is enough.

----
    Argument: -1 violated a precondition: i >= 0
----

So, I would think of a small method as follows.

[source,java]
----
public class Hello {
  public void helloAssertThat(double var) {
    double checkedVar = require(var, v -> v >= 0.0 && v < 20.0);
    System.out.println(checkedVar);
  }

  public static <T> T require(T value, Predicate<? super T> cond) {
    if (!cond.test(value))
      throw new IllegalArgumentException(String.format("Value: %s violated: %s", value, cond));
    return value;
  }
}
----

Unfortunately in Java, `toString` on lambda results in a cryptic string.

[console]
----
java.lang.IllegalArgumentException: Value:20.0 violated: com.github.dakusui.pcond.examples.Example$$Lambda$1/537548559@5680a178

	at Hello.require(AssertionProviderBase.java:99)
----

`pcond` is a library to build printable functions and predicates to fix it.

[source,java]
----
public class HelloPcond {
  public void helloAssertThat(double var) {
    double checkedVar = requireArgument(var, ge(0.0).and(lt(20.0)));
    System.out.println(checkedVar);
  }
}
----

This will print as message shown below.

[console]
----
java.lang.IllegalArgument: Value: 20.0 violated: (>=[0.0]&&<[20.0])
	at com.github.dakusui.pcond.Preconditions.requireArgument(Assertions.java:16)
    ...
----

It also comes with fancy features like

- Zero-overhead `assert` style
- Fluent style
- Design by Contract supporting methods in both styles
- Customizable Exception/Message Policy mechanism (`AssertionProvider`)
- "Transform and check" predicate building mechanism
- Predicates and functions returned by `pcond` returned from the same method with the same arguments in `pcond` API are `equalTo` each other.
And `hashCode` methods are also implemented in a way Java API's standard requires.

Enjoy!

== Installation

[source,xml]
----
<dependency>
    <groupId>com.github.dakusui</groupId>
    <artifactId>pcond</artifactId>
    <packaging>jar</packaging>
    <version>${pcond.version}</version>
</dependency>
----

For `${pcond.version}`, `1.1.0-SNAPSHOT` is the latest one as of Mar/15/2020.

== Getting started

Import entry points of this library statically.

[source,java]
----
import static com.github.dakusui.pcond.Assertions.*;
import static com.github.dakusui.pcond.Preconditions.*;
import static com.github.dakusui.pcond.Validations.*;
import static com.github.dakusui.pcond.functions.Functions.*;
import static com.github.dakusui.pcond.functions.Predicates.*;

----

=== Fluent Style

[source,java]
----
class FluentStatementStyle {
  public int example(int i, int j) {
    require(i, ge(0).and(lt(20)));
    require(j, ge(0).and(lt(40)));
    int ret = i + j;
    return ensure(ret, ge(0).and(lt(40)));
  }
}
----

Methods defined in `Preconditions`, `Postconditions`, and `Validations` class are designed to return the given value to be able to avoid unnecessary assignments.

With the methods, you can write the same code in a following style, either.

[source,java]
----
class FluentStatementStyle {
  public void example(int i, int j) {
    return ensure(
        require(i, ge(0).and(lt(20))) + require(j, ge(0).and(lt(40))),
        ge(0).and(lt(40)));
  }
}
----

=== Assert statement Style

Another style to describe pre/post-conditions is to use `assert` statement.

[source,java]
----
class AssertStatementStyle {
  public void example(int i) {
    assert that(i, ge(0).and(lt(20)));
  }
}
----

In spite that the `assert` statement in the example has only one argument, still it gives you a readable message.
The trick is that the method `that` throws an `AssertionFailure` with a composed message rather than simply returning `false` returned from a given predicate.
(It will never return `false`, in other words)

In order to be explicit the purpose of an assertion, the `Assertion` class has also `precondition` and `postcondition` methods.

[source,java]
----
class AssertStatementStyle {
  public void example(int i, int j) {
    assert precondition(i, ge(0).and(lt(20)));
    assert precondition(j, ge(0).and(lt(20)));

    int ret = i + j;

    assert postcondition(ret, ge(0).and(lt(40)));
  }
}
----

Great point of this approach is to be able to eliminate the overhead coming from the assertion just by giving `-da` option to your JVM, yet we can get informative messages on a failure.

By default, `precondition`, `postcondition`, and `that` methods throw `AssertionFailure` and behave the same.
They are defined separately in order to make it possible to customize the behaviors independently by implementing a custom `AssertionProvider`.

=== Validation

(t.b.d.)

=== Transforming Predicate

(t.b.d)

== Features

* Pre-condition check
* Post-condition check
* Validation
* Readable in source code and output on error
* Fluent style
* `assert` style (zero overhead)
* Zero-overhead readable assertion message (with `assert {that, precondition, postcondition}` style and `-da` option)
* Transforming predicate.

[bibliography]
== References

(t.b.d.)

* https://github.com/google/guava/wiki/PreconditionsExplained[Preconditions Explaind, Google Guava]

- [[[v4j]]] Valid4j, http://www.valid4j.org
- [[[DbC]]] Wikipedia article on Design by Contract, https://en.wikipedia.org/wiki/Design_by_contract