= The `pcond` library

`pcond` is a library to build "printable" predicates to build conditions that generate informative messages on failures.

== Background

In programmings, checking a value if it satisfies a given condition is a common and wide-spread concern.
Is a value is `null` or not.
Is a given number positive or zero?
Isn't a string empty?
Does it have a length longer than a certain value?
Does a given object has a name which doesn't contain any value?
And more.
For each of them, we may want a proper message.
All of these can happen in a context of input value checking of a library function, validations in API entry point, assertions in unit testing, {pre,post}-condition checks in Design by Contract style programming.

However, especially in Java, there is no good uniformed solution to them.
For value checking in a normal product code, we may use `Validate` class (Apache Commons), `Preconditions` class (Google Guava), or just create our own class check and compose error messages on check failures.
For Unit Testing, classes called in many ways are used for defining conditions to check the validity of values such as `Matcher`<<hamcrest>>, `Assert`<<assertj>> or `Subject`<<google-truth>>.
For Design by Contract, some relies on annotations to define contracts<<java-dbc>>, some other re-uses a test assertion library for it<<valid4j>>.

Every solution in every context above provides a user with a way to override messages that it generates because a library cannot always compose a sufficiently informative and helpful message automatically.
But such hand-crafted messages tend to be stale easily over time.

Thus, in spite that the same concern is shared among wide areas, no good solution has been provided and the concern is addressed in quite ad hoc manners depending on the contexts.

`pcond` is a library that provides a uniformed solution to all the use-cases above.

== Key Concepts

* Printable Predicates
* Composable Predicates
* Transform-and-Check Programming Model
* Printable Predicates
* Entry-points: `Predicates`, `Functions`, and `Printables`
  ** `isEqualTo` (`Predicates`)
  ** `call` (`Functions`)
* Fluent API to build printable predicates

=== Transform-and-Check Programming Model

(t.b.d.)

=== Printable Predicates

(t.b.d.)

=== Entry-points

==== Predicates

(t.b.d.)

==== Functions

(t.b.d.)

=== Fluent API to build printable predicates

== Experimental Features: `Experimentals`

* `Experimentals`
  ** `nest`
  ** Currying mechanism and a context.
  ** Multi-parameter Functions

== Design Detail

* Evaluator mechanism
* Configuration mechanism

[bibliography]
== References

- [[[thincrest-pcond, 1]]] thincrest-pcond
- [[[hamcrest, 2]]] Hamcrest, Matchers that can be combined to create flexible expressions of intent, https://hamcrest.org/
- [[[assertj, 3]]] AssertJ, Fluent assertions for java, https://joel-costigliola.github.io/assertj/
- [[[google-truth, 3]]] Truth - Fluent assertions for Java and Android, https://truth.dev/
- [[[valid8j, 4]]] valid8j
- [[[valid4j, 5]]] valid4j https://www.valid4j.org/
- [[[DbCbyExample, 6]]] "Design by Contract, by Example" by Richard Mitchell and Jim McKim, 2002, Jim McKim, Richard Mitchell
- [[[power-assert, 8 ]]] power-assert https://github.com/power-assert-js/power-assert
- [[[java-power-assert, 9]]] java-power-assert https://github.com/jkschneider/java-power-assert
- [[[java-dbc, 10]]] Java DbC https://github.com/neopragma/java-dbc