
= The `pcond` library

`pcond` is a simple library to build "printable" predicates.
Why is it important and worth providing a library?
Alright, let me explain it first.

== Background
A small but everyday programming pain in Java is its lack of "introspection" over Lambdas.
I mean, we always do something like:

[source,java]
----
import java.util.Arrays;class Example {
  static void method(String... args) {
    require(args,
            v -> v != null && v.lenth > 1,
            v -> "We expect input should be non-null and its length is " +
                 "greater than 1 but it was:<" + Arrays.toString(v) + ">");
  }

  static void require(
          String[] args,
          Predicate<String[]> requirement,
          Function<String[], String> messageFormatter) {
    if (!requirement.test(args))
      throw new IllegalArgumentException(messageFormatter.apply(args));
  }
}
----

This is obviously error-prone.
When we want to make the `method` accept a string array whose length is larger than 2, we also need to edit the message string, which you may forget, sometimes.
If we could print the definition of the lambda with the value given to it, our life will become easier.

Actually, for instance, JavaScript, it is possible.
There is a library called `power-assert`[<<power-assert>>].
It allows you to do it.

[source]
----
  1) Array #indexOf() should return index when the value is present:
     AssertionError: # path/to/test/mocha_node.js:10

  assert(ary.indexOf(zero) === two)
         |   |       |     |   |
         |   |       |     |   2
         |   -1      0     false
         [1,2,3]

  [number] two
  => 2
  [number] ary.indexOf(zero)
  => -1
----

Although this approach may not allow us to define the error message fully human-friendly, but this will be usually sufficient for developers.

To our knowledge, only one known attempt to achieve it in Java is `java-power-assert`[<<java-power-assert>>].
However, the library's binary is not available in public any more as of Oct, 2023 and not developed actively.
Instead, several other approaches were attempted in Java's ecosystem.

=== Existing Approaches Other Than Introspection

To check a condition and to produce a reasonably human-friendly error message for the condition is a common concern for some areas such as test assertions, assertions in Design by Contract programming style, and value checking in programming in general.
Let's now take a look at those existing approaches and their pain points.

==== Test Assertion Libraries

In automated testing, it is essential to provide a user friendly message when a given condition is broken (resulting in `false` or failed to evaluate by an exception).
In Java's ecosystem, there are a few well-known test assertion libraries such as Hamcrest[<<hamcrest>>], AssertJ[<<assertj>>], or Google Truth[<<google-truth>>].

**Hamcrest:** Hamcrest[<<hamcrest>>] is the first one among them and all the assertion libraries in Java.
Following is an example picked up from Baelung's blog post[<<baeldung-hamcrest>>].

[source, java]
.An example from [<<baeldung-hamcrest>>], modified to make it fail.
----
public class Example {
    @Test
    public void givenBean_whenToStringReturnsRequiredString_thenCorrect(){
        Person person=new Person("Barrack", "Washington");
        assertThat(person, hasToString("[Biden]"));
    }
}
----
The static method `hasToString(String)` is defined in `org.hamcrest.Matchers` class and it returns a `Matcher` object.
If this example fails with a human-friendly error message as follows:

----
java.lang.AssertionError:
Expected: with toString() "[Biden]"
     but: toString() was "[Barrack, Washington]"

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
----

Nevertheless, Hamcrest has the following challenges.

- Designed only for test assertions.
Cannot be used for other purposes such as value checking or DbC style assertions in general.
- Steep learning curve.
Factory methods to create matchers are provided as static methods or plain Java class.
Users need to memory which classes or static methods are useful for what use cases.
- Expensive to provide a support for a custom type (class), even if possible.

**AssertJ:** AssertJ is another assertion library.
It has a "fluent" style API and it reduces the pain to learn its programming model.

[source, java]
.AssertJ example
----
import static org.assertj.core.api.Assertions.*;

public class PersonTest {

    @Test
    public void testNameAndAge() {
        Person person = new Person("Alice", 30);

        assertThat(person.getName())
            .isNotNull()
            .isEqualTo("Alice")
            .startsWith("Al")
            .endsWith("ce")
            .contains("lic");

        assertThat(person.getAge())
            .isGreaterThan(20)
            .isLessThanOrEqualTo(30);
    }
}
----

**Google Truth:** (t.b.d.)

==== `Validate` class of Apache `commons-lang` library

Apache `commons-lang` library[<<commons-lang>>] provides `Validate` class[<<commons-lang-Validate>>].
(t.b.d.)

- Not composable.
- Gives information only for failed condition.
No information about already passing conditions nor not yet exercised conditions.

==== `valid4j`, a DbC library

(t.b.d.)

== The `pcond` 's Approach


[source,java]
----
public class Example {
  private void privateMethod(String message) {
    assert precondition(message, isNotNull()); //<1>
    System.out.println(mesage);
  }
}
----
<1> This line is not executed at all if you give `-da` option to your JVM.



== References

- [[power-assert, 1]] power-assert https://github.com/power-assert-js/power-assert[power-assert]: 2021
- [[java-power-assert, 2]] java-power-assert https://github.com/jkschneider/java-power-assert[java-power-assert]: 2016
- [[commons-lang, 3]] commons-lang https://commons.apache.org/proper/commons-lang/[commons-lang]:2023
- [[commons-lang-Validate, 4]] Validate.class https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/Validate.html[commons-lang-Validate]:2023
- [[hamcrest, 5]] Hamcrest https://hamcrest.org/[Hamcrest]:2012-2023
- [[assertj, 6]] AssertJ
- [[google-truth, 7]] Google Truth
- [[baeldung-hamcrest, 8]] baeldung.com/java-junit-hamcrest-guide https://baeldung.com/java-junit-hamcrest-guide[baeldung.com/java-junit-hamcrest-guide]